# ~/.config/starship.toml

format = "$time $directory $git_branch $gcloud \n$character"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[time]
disabled = false
format = "[$time]($style) "
time_format = "%d-%b-%y %-I:%M%P"

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 2
# [directory.substitutions]
# '/Users/abdullahzaidas-sani/scripts/' = 'ðŸ“‚ Scripts'
# '/Users/abdullahzaidas-sani/projects/gamuda' = 'ðŸ“‚ Gamuda'
# 'Users/abdullahzaidas-sani' = 'ðŸ“‚ Home'
# 'Users/abdullahzaidas-sani/Downloads' = 'ðŸ“‚ Downloads'

[git_branch]
symbol = "ðŸŒ± "

[character]
success_symbol = "[âžœ](bold green)"
error_symbol = "[âžœ](bold red)"
