# Reference: https://github.com/i3/i3/blob/next/etc/config
# Reference: https://github.com/adriankarlen/dots/blob/main/.config/aerospace/aerospace.toml

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
after-login-command = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']


# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    # 'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar',
    # 'exec-and-forget'
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    # '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]


# [workspace-to-monitor-force-assignment]
# 1 = 2
# 2 = 2 
# 3 = 2 
# 4 = 2
# 5 = 1 
# 6 = 1
# 7 = 1
# 8 = 3 
# 9 = 3 
# 10 = 3   

[workspace-to-monitor-force-assignment]
# 1 is 2nd monitor, 3 is vertical monitor, for some reason idk
1 = [1,'built-in']
2 = [1,'built-in']
3 = [1,'built-in']
4 = [1,'built-in']
5 = [2,'built-in']
6 = [2,'built-in']
7 = [3,'built-in']
8 = [3,'built-in']
9 = [3,'built-in']
10 = [3,'built-in']

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]

# --- Go to workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-q = 'workspace 6'
    alt-w = 'workspace 7'
    alt-e = 'workspace 8'
    alt-r = 'workspace 9'
    alt-t = 'workspace 10'   

# --- Move window to workspace
    alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    alt-shift-q = 'move-node-to-workspace 6 --focus-follows-window'
    alt-shift-w = 'move-node-to-workspace 7 --focus-follows-window'
    alt-shift-e = 'move-node-to-workspace 8 --focus-follows-window'
    alt-shift-r = 'move-node-to-workspace 9 --focus-follows-window'
    alt-shift-t = 'move-node-to-workspace 10 --focus-follows-window'

    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    # alt-q = '''exec-and-forget osascript -e '
    # tell application id "com.mitchellh.ghostty"
    #     do script 
    #     activate
    # end tell'
    # '''

    # alt-q = 'exec-and-forget open -a "Ghostty" -n'
    # alt-b = 'exec-and-forget open -a "Vivaldi" -n'
    # alt-v = 'exec-and-forget open -a "Whatsapp" -n'
    # alt-b = 'exec-and-forget open -a "Zen" -n'

    # i3 wraps focus by default
    alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-j =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    # alt-g = 'split horizontal'
    # alt-v = 'split vertical'

    alt-p = 'fullscreen'
    alt-shift-p = 'macos-native-fullscreen'

    
    alt-o = 'focus-back-and-forth'
    alt-8 = 'layout v_accordion' # 'layout stacking' in i3
    alt-9 = 'layout h_accordion' # 'layout tabbed' in i3
    alt-0 = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-f = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent#
    #
    # alt-tab = 'workspace-back-and-forth'

    # alt-shift-r = 'reload-config'

    # resizing
    alt-minus = 'resize smart -70'
    alt-equal = 'resize smart +70'

    alt-ctrl-r = 'mode resize'
    

# Floating
[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'FreeTube'
run = 'layout floating'  
[[on-window-detected]]
if.app-name-regex-substring = 'IINA'
run = 'layout floating'  
[[on-window-detected]]
if.app-name-regex-substring = '1Password'
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'Todoist'
run = [
    # 'move-node-to-workspace 9',
    'layout floating',
]
# Workspace 3 - Apps
[[on-window-detected]]
if.app-name-regex-substring = 'Docker'
run = 'move-node-to-workspace 3'

# Workspace 4 - News
[[on-window-detected]]
if.app-name-regex-substring = 'NetNewsWire'
run = 'move-node-to-workspace 4'

# Workspace 5 - Terminal
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = [
  "layout floating",
  "move-node-to-workspace 5",
]

# Workspace 6 - MAIN


# Workspace 7 - Note
[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace 7'

# Workspace 8 - AI
[[on-window-detected]]
if.app-name-regex-substring = 'T3 Chat'
run = 'move-node-to-workspace 8'

# Workspace 9 - Emails & Tasks
[[on-window-detected]]
if.app-name-regex-substring = 'Fantastical'
run = 'move-node-to-workspace 9'
[[on-window-detected]]
if.app-name-regex-substring = 'Thunderbird'
run = 'move-node-to-workspace 9'
[[on-window-detected]]
if.app-name-regex-substring = 'Outlook'
run = 'move-node-to-workspace 9'

# Workspace 10  - Chats
[[on-window-detected]]
if.app-name-regex-substring = 'Messages'
run = 'move-node-to-workspace 10'
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 10'
[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace 10'
[[on-window-detected]]
if.app-name-regex-substring = 'Telegram'
run = 'move-node-to-workspace 10'
[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 10'

# [[on-window-detected]]
#   if.app-id = 'com.github.th-ch.youtube-music'
#   run = 'move-node-to-workspace 5'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# AEROSPACE SWIPE
# https://github.com/acsandmann/aerospace-swipe
